OctopusReactNativeSdk_kotlinVersion=2.1.10
OctopusReactNativeSdk_minSdkVersion=24
OctopusReactNativeSdk_targetSdkVersion=34
OctopusReactNativeSdk_compileSdkVersion=35
OctopusReactNativeSdk_ndkVersion=27.1.12297006
OctopusReactNativeSdk_composeBomVersion=2025.10.00
OctopusReactNativeSdk_androidXNavigationVersion=2.9.0

OctopusReactNativeSdk_octopusCommunityVersion=1.13.2
